Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  config.vm.box = 'ubuntu/trusty64'
  config.vm.network "private_network", ip: '192.168.33.20'
  config.vm.hostname = 'rails-sample'
  config.vm.synced_folder '../', '/srv/src',
    :id => 'vagrant-root', :nfs => true

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/vagrant.yml"
    ansible.inventory_path = "../ansible/hosts"
    ansible.limit = 'all'
  end
end
